"""End-to-end Phase 3 acceptance: walk → chunk → embed → write → query.

Mocks the embedding HTTP endpoint with a deterministic hash-based vector
so no Ollama is required. The Brunnr backend is the real sqlite_vec
adapter writing to a tmp_path.
"""

from __future__ import annotations

import hashlib
from collections.abc import Sequence
from pathlib import Path

import pytest

pytest.importorskip("sqlite_vec")

from ember.schemas.config import (
    BrunnrConfig,
    ChunkerConfig,
    EmbeddingConfig,
    JournalConfig,
    SmidjaConfig,
    SqliteVecConfig,
)
from ember.well.brunnr.sqlite_vec import SqliteVecBrunnr
from ember.well.brunnr.sqlite_vec import open as sv_open
from ember.well.smidja.local_files import run

_DIM = 32


class _DeterministicEmbedClient:
    """Stable, content-addressed embeddings — no network."""

    def embed(self, texts: Sequence[str]) -> list[tuple[float, ...] | None]:
        out: list[tuple[float, ...] | None] = []
        for text in texts:
            out.append(_hash_to_vector(text, _DIM))
        return out


def _hash_to_vector(text: str, dim: int) -> tuple[float, ...]:
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    while len(digest) < dim * 4:
        digest += hashlib.sha256(digest).digest()
    values = [int.from_bytes(digest[i * 4 : (i + 1) * 4], "little") / 2**32 for i in range(dim)]
    return tuple(values)


def _make_brunnr(path: Path) -> SqliteVecBrunnr:
    cfg = BrunnrConfig(
        embedding_dim=_DIM,
        sqlite_vec=SqliteVecConfig(path=path),
    )
    handle = sv_open(cfg)
    assert isinstance(handle, SqliteVecBrunnr)
    return handle


def _smidja_config(journal_root: Path) -> SmidjaConfig:
    return SmidjaConfig(
        embedding=EmbeddingConfig(),
        chunker=ChunkerConfig(max_chars=400, target_chars=250, min_chars=20),
        journal=JournalConfig(root=journal_root),
    )


def test_ingest_then_query_round_trip(tmp_path: Path) -> None:
    notes = tmp_path / "notes"
    notes.mkdir()
    (notes / "odin.md").write_text(
        "Odin is the Allfather of the Norse pantheon. He sacrificed an eye for wisdom.\n\n"
        "Odin rules from his hall Valhalla. His ravens Huginn and Muninn fly the worlds.",
        encoding="utf-8",
    )
    (notes / "thor.md").write_text(
        "Thor is the god of thunder. He wields the hammer Mjolnir.\n\n"
        "Thor defends Midgard from giants. He drives a chariot pulled by goats.",
        encoding="utf-8",
    )

    brunnr = _make_brunnr(tmp_path / "store.db")
    cfg = _smidja_config(tmp_path / "journal")

    summary = run(
        brunnr,
        root=notes,
        smidja_config=cfg,
        embed_client=_DeterministicEmbedClient(),
    )

    assert summary.n_documents == 2
    assert summary.n_chunks >= 2
    assert summary.n_failed == 0
    assert summary.elapsed_s >= 0

    # Round-trip: text search recovers a chunk we wrote.
    text_hits = brunnr.text_search("Mjolnir", k=5)
    assert any("Mjolnir" in h.text for h in text_hits)

    # Round-trip: vector search returns the same chunk for an
    # embedding generated by the same deterministic hash.
    qvec = _hash_to_vector("Thor is the god of thunder. He wields the hammer Mjolnir.", _DIM)
    vec_hits = brunnr.vector_search(qvec, k=3)
    assert len(vec_hits) >= 1

    # Stats reflect what we ingested.
    stats = brunnr.count()
    assert stats.documents == 2
    assert stats.chunks == summary.n_chunks
    assert stats.embedded_chunks == summary.n_chunks

    brunnr.close()


def test_resume_skips_already_done_files(tmp_path: Path) -> None:
    notes = tmp_path / "notes"
    notes.mkdir()
    (notes / "a.md").write_text("Odin sacrificed an eye for wisdom.", encoding="utf-8")
    (notes / "b.md").write_text("Thor wields Mjolnir against giants.", encoding="utf-8")

    brunnr = _make_brunnr(tmp_path / "store.db")
    cfg = _smidja_config(tmp_path / "journal")
    client = _DeterministicEmbedClient()

    first = run(brunnr, root=notes, smidja_config=cfg, embed_client=client)
    assert first.n_documents == 2
    initial_chunks = brunnr.count().chunks

    # A re-run after journal.complete() starts a fresh journal but
    # add_document is idempotent on hash — net chunks stay the same.
    second = run(brunnr, root=notes, smidja_config=cfg, embed_client=client)
    assert brunnr.count().chunks == initial_chunks
    assert second.n_documents == 2  # documents still walked; idempotent at Brunnr layer

    brunnr.close()


def test_embed_failure_for_one_chunk_is_recorded_and_continues(tmp_path: Path) -> None:
    notes = tmp_path / "notes"
    notes.mkdir()
    (notes / "doc.md").write_text(
        "First paragraph about Odin.\n\n"
        "Second paragraph about Thor.\n\n"
        "Third paragraph about Freyja.",
        encoding="utf-8",
    )

    class _FlakyClient:
        def embed(self, texts: Sequence[str]) -> list[tuple[float, ...] | None]:
            # Fail chunk index 1; succeed for the rest.
            return [
                None if i == 1 else _hash_to_vector(t, _DIM)
                for i, t in enumerate(texts)
            ]

    brunnr = _make_brunnr(tmp_path / "store.db")
    # Tight chunker config so each paragraph becomes its own chunk —
    # otherwise the whole doc fits in one and there's nothing for the
    # flaky client's index-1 failure to act on.
    cfg = SmidjaConfig(
        embedding=EmbeddingConfig(),
        chunker=ChunkerConfig(max_chars=40, target_chars=30, min_chars=5),
        journal=JournalConfig(root=tmp_path / "journal"),
    )

    summary = run(
        brunnr,
        root=notes,
        smidja_config=cfg,
        embed_client=_FlakyClient(),
    )

    # Two chunks should have been written; one failed but the document
    # itself counts as ingested.
    assert summary.n_documents == 1
    assert summary.n_chunks == 2
    assert summary.n_failed == 1

    brunnr.close()
