"""
E2E Build Script — Auto-generated by hamr.blender_bridge.e2e
Spec: anime_girl_default
GPU Profile: pi5
Generated: 2026-05-16 23:08:35
"""

import json
import sys
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────────
SPEC_NAME = "anime_girl_default"
GPU_PROFILE = "pi5"
VALIDATE = True
VERBOSE = False
OUTPUT_DIR = r"build_output"
SPEC_DATA = {
  "name": "Default Schoolgirl",
  "body": {
    "height_cm": 158.0,
    "build": "average",
    "skin": {
      "base_hex": "#F5D6C3",
      "undertone": "warm",
      "freckles": false,
      "tan_level": 0.4
    },
    "proportions": {
      "shoulder_width": 0.35,
      "bust": 0.55,
      "waist": 0.3,
      "hip_width": 0.6,
      "leg_length": 0.55
    }
  },
  "face": {
    "jaw": "V-shape",
    "cheekbones": "high",
    "eyes": {
      "iris_hex": "#8B5E3C",
      "shape": "round",
      "size": 1.3
    },
    "nose_size": "small",
    "nose_bridge": "narrow",
    "lip_fullness": 0.6,
    "default_expression": "soft-half-smile"
  },
  "hair": {
    "style": "straight",
    "length": "long",
    "volume": 0.7,
    "curl_tightness": 0.0,
    "color": {
      "roots": "#5C3A1E",
      "mid": "#7A4E28",
      "tips": "#A06830"
    },
    "shell_layers": 4
  },
  "clothing": [
    {
      "name": "school_uniform",
      "type": "full-outfit",
      "primary_hex": "#1A1A3E",
      "accent_hex": "#FFFFFF",
      "trim_hex": "#C0392B"
    }
  ],
  "expressions": {
    "defaults": {
      "blink": "subtle",
      "blush": "always-on"
    },
    "custom": []
  },
  "physics": {
    "hair": {
      "stiffness": 0.3,
      "gravity": 0.25,
      "drag": 0.35
    },
    "breast": {
      "stiffness": 0.25,
      "drag": 0.6
    }
  }
}
SPEC_OVERRIDES = {}
BUILD_STAGES = ['clear_scene', 'import_base', 'apply_spec', 'integrate_stub_bones', 'integrate_hair_mesh', 'integrate_clothing_mesh', 'integrate_weight_paint', 'integrate_spring_bones', 'integrate_first_person', 'apply_vrm_humanoid', 'apply_vrm_metadata', 'apply_vrm_expressions', 'apply_vrm_look_at', 'export_vrm', 'post_export_validation']

# ── Estimated Stats ──────────────────────────────────────────────────────
ESTIMATED_TRIANGLES = 15000
ESTIMATED_MESHES = 6
ESTIMATED_BONES = 55

# ── Apply Overrides ──────────────────────────────────────
def deep_merge(base, override):
    """Recursively merge override dict into base dict."""
    for key, value in override.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            deep_merge(base[key], value)
        else:
            base[key] = value
    return base

if overrides_json:
    spec_json = deep_merge(dict(spec_json) if isinstance(spec_json, dict) else {}, overrides_json)


def main():
    """Main build entry point — runs inside Blender."""
    stages_completed = []
    stages_failed = []

    # Check for Blender
    try:
        import bpy  # type: ignore
    except ImportError:
        print("ERROR: This script must run inside Blender (bpy not available)")
        return 1

    print(f"[E2E] Starting build: {SPEC_NAME} on {GPU_PROFILE} profile")
    print(f"[E2E] Estimated triangles: {ESTIMATED_TRIANGLES}")
    print(f"[E2E] Estimated meshes: {ESTIMATED_MESHES}")
    print(f"[E2E] Estimated bones: {ESTIMATED_BONES}")

    output_path = Path(OUTPUT_DIR) / f"{SPEC_NAME}.vrm"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write spec to temp file for build_avatar.py
    spec_temp = output_path.parent / f".hamr_{SPEC_NAME}_spec.json"
    spec_temp.write_text(json.dumps(SPEC_DATA, indent=2))

    # Import the build script and run
    try:
        from hamr.scripts.build_avatar import main as build_main
        sys.argv = sys.argv[:1] + [
            "--", "--spec", str(spec_temp),
            "--output", str(output_path),
        ]
        result = build_main()
        if result == 0:
            print(f"[E2E] Build completed successfully: {output_path}")
        else:
            print(f"[E2E] Build failed with exit code: {result}")
            stages_failed.append("build_main")
        return result
    except Exception as e:
        print(f"[E2E] Build exception: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
